/**
 * The travel icon set behind "Most popular destinations": Fluent Emoji for each link and a
 * one-colour glyph for each card header, both rendered with @iconify/react. The files are
 * generated by scripts/travel-icons.mjs; the dashboard's icon pickers offer the same list.
 *
 * Emoji are one file each and loaded on demand, so the page only downloads the ones the CMS
 * actually uses. The glyphs are tiny and ship with the bundle.
 */
import catalog from '../assets/travel-icons/catalog.json';
import glyphs from '../assets/travel-icons/glyphs.json';

export { glyphs };

// Card tones, in the order a card gets them when the dashboard has not chosen one.
export const TONES = ['blue', 'orange', 'pink', 'green', 'purple', 'yellow', 'teal'];

const emojiInfo = new Map(catalog.emoji.map((e) => [e.name, e]));
const loaders = import.meta.glob('../assets/travel-icons/emoji/*.json', { import: 'default' });
const loaded = new Map();

export const isEmoji = (name) => emojiInfo.has(name);
export const isGlyph = (name) => Object.prototype.hasOwnProperty.call(glyphs, name);

/** The soft colour behind an emoji's little tile. */
export const emojiTile = (name) => emojiInfo.get(name)?.tile || 'sky';

/** Icon data already in memory, so a re-render does not flash an empty tile. */
export const peekEmoji = (name) => loaded.get(name) || null;

export const loadEmoji = (name) => {
  if (loaded.has(name)) return Promise.resolve(loaded.get(name));
  const load = loaders[`../assets/travel-icons/emoji/${name}.json`];
  if (!load) return Promise.resolve(null);
  return load()
    .then((data) => {
      loaded.set(name, data);
      return data;
    })
    .catch(() => null);
};

// Whole words only: the resort "Side" must not match "Seaside", nor "car" match "Caribbean".
const escape = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const hasWord = (text, word) =>
  new RegExp(`(^|[^\\p{L}\\p{N}])${escape(word)}(?=$|[^\\p{L}\\p{N}])`, 'iu').test(text);

/** The emoji for a link the dashboard left without one, from its label and place. */
export const inferLinkIcon = (...texts) => {
  const text = texts.filter(Boolean).join(' ');
  if (!text) return null;
  const rule = catalog.destinationRules.find(([words]) => words.some((w) => hasWord(text, w)));
  return rule ? rule[1] : null;
};

/** A card's header glyph and tone when the dashboard has not set them, from its title. */
export const inferGroupStyle = (title) => {
  const text = String(title || '');
  const rule = catalog.groupRules.find(([words]) => words.some((w) => hasWord(text, w)));
  return rule ? { glyph: rule[1], tone: rule[2] } : null;
};
